# @format
name: CI/Push

on:
  push:
    branches:
      - main
      - test

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install dependecies
        run: npm ci

      - name: Coverage
        run: npm run coverage
